name: Code Coverage

on:
  push:
    branches: [main]
    paths:
      - 'Package.swift'
      - 'Sources/**'
      - 'Tests/**'
  pull_request:
    paths:
      - 'Package.swift'
      - 'Sources/**'
      - 'Tests/**'
      - '.github/workflows/code-coverage.yml'

jobs:
  code-coverage:
    uses: request-dl/.github/.github/workflows/code-coverage.yml@main
    with:
      xcode-version: 14.3.1
      platform: macOS-13
      package-tests: swift-openapi-request-dlPackageTests
      target: OpenAPIRequestDL
    secrets: inherit
