name: Documentation

on:
  workflow_dispatch:
  release:
    types:
      - published

jobs:
  documentation:
    permissions:
      contents: read
      pages: write
      id-token: write
    uses: request-dl/.github/.github/workflows/documentation.yml@main
    with:
      swift-version: 5.8
      platform: macOS-13
      target: OpenAPIRequestDL
      hosting-base-path: swift-openapi-request-dl
      output: ./_site
    secrets: inherit
